### ISSUE TITLE
Design API

### ISSUE THREAD

**Issue by korn-alex** [dev-Toumeh/basement-organizer#10]
## Functions
- **login**
- **register**
- **view_create_modify_item**
  - label
  - description
  - quantity
  - picture
- **delete_item**
- **create_modify_box**
  - label
  - description
  - picture
- **view_items_in_box_or_area**
- **move_items_in_out_of_box**
- **move_boxes_in_out_of_box**
- **delete_box**
- **view_create_modify_room_or_area**
  - difference_with_box
- **search_for_item_box**
- **create_QR_code_for_item_box**

## Place
- **room**
  - label
  - description
  - items
- **box**
  - label
  - description
  - items
  - picture
  - QR_code

## Item
- label
- description
- picture
- quantity
- QR_code

**Comment by dev-Toumeh** [comment]
you need also to add those following functions:
- create_Shelving_unit
